name = "copytrade-signal-bot"
main = "worker/index.js"
compatibility_date = "2024-09-23"

[triggers]
crons = ["*/1 * * * *"]

[[kv_namespaces]]
binding = "BOT_STATE"
id = "ef449f2aa2eb4afda4262e5db75d1b8d"
